spring:
  application:
    name: academic-events-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    open-in-view: false

  jackson:
    time-zone: UTC
  web:
    error:
      include-message: always
      include-binding-errors: always

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true